apiVersion: zookeeper.zncdata.dev/v1alpha1
kind: ZookeeperZnode
metadata:
  labels:
    app.kubernetes.io/name: zookeeperznode
    app.kubernetes.io/instance: zookeeperznode-sample
    app.kubernetes.io/part-of: zookeeper-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: zookeeper-operator
  name: zookeeperznode-sample
spec:
  clusterRef:
    name: zookeepercluster-sample






