apiVersion: zookeeper.zncdata.dev/v1alpha1
kind: ZookeeperCluster
metadata:
  labels:
    app.kubernetes.io/name: zookeepercluster
    app.kubernetes.io/instance: zookeepercluster-sample
    app.kubernetes.io/part-of: zookeeper-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: zookeeper-operator
  name: zookeepercluster-sample
spec:
  clusterConfig:
    listenerClass: external-unstable
  server:
    config:
      resources:
        cpu:
          min: "1"
          max: "2"
        memory:
          limit: "2Gi"
    roleGroups:
      default:
        replicas: 3
        config:
          resources:
            cpu:
              min: "1"
              max: "2"
            memory:
              limit: "3Gi"
          logging:
            zookeeperCluster:
              loggers:
                test:
                  level: DEBUG
              console:
                level: WARN
              file:
                level: INFO



